kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch
  namespace: skywalking
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-t6sq2d
          image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.0'
          ports:
            - name: http-9200
              containerPort: 9200
              protocol: TCP
            - name: http-9300
              containerPort: 9300
              protocol: TCP
          env:
            - name: node.name
              value: node-1
            - name: cluster.initial_master_nodes
              value: node-1
            - name: cluster.name
              value: elasticsearch7
            - name: network.host
              value: 0.0.0.0
            - name: ES_JAVA_OPTS
              value: '-Xmx1g -Xms1g'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-svc
  namespace: skywalking
  labels:
    app: elasticsearch-svc
spec:
  ports:
    - name: http-9200
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: http-9300
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
  type: ClusterIP

